#!/usr/bin/env bash

# Program to add movie

echo "What is the name of the movie?"
read movie_name
echo "Which year was the film released?"
read year
echo "Which genre is the film?"
read genre

entry="$movie_name^$year^$genre^"

# add this entry to the end of the file
echo "$entry" >> $CATALOG_LOCATION
# sort and redirect output to file
sort -o $CATALOG_LOCATION $CATALOG_LOCATION
echo 
echo "$movie_name has been added to the movie catalog"

echo "Would you like to add another movie to the catalog (y/n)?"
read answer 
if [ "$answer" = "y" ] ; then 
    add;
fi