#!/usr/bin/env bash

# remove entry from movies

name=$1

# Get matching entries and save in temp file

grep -i "$name" $CATALOG_LOCATION > /tmp/matches$$
# if file size is 0
if [ ! -s /tmp/matches$$ ] ; then
    echo "I can't find $name in movie catalog"
    exit 1
fi

# display matching entries and confirm removal

while read line
do
    display "$line"
    echo -e "Remove this title from catalog (y/n)? \c"
    read answer < /dev/tty

    if [ "$answer" = y ] ; then
        break
    fi
done < /tmp/matches$$

rm /tmp/matches$$

if [ "$answer" = y ] ; then
    # pipe all lines that do NOT match
    grep -i -v "^$line$" $CATALOG_LOCATION > /tmp/movies$$
    mv /tmp/movies$$ $CATALOG_LOCATION
    echo "Selected entry has been removed"
    if [ ! -s $CATALOG_LOCATION ] ; then
        echo "Note: You don't have any movies :( "
    else
        echo "Entry not removed"
    fi
fi
